version: "1.0"
services:
  backend:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8080:8080"

  frontend:
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
